### ISSUE TITLE
Process submission format for nuScenes challange

### ISSUE THREAD

**Issue by minano430** [wasn-lab/Multimodal_Transformer#12]
# TODO To submit the result to https://eval.ai/web/challenges/challenge-page/591/overview

- [ ] Know the measurement matrix of competition (@minano430)
- [ ] Know the submission file format
    - [ ]  Execute nuScene baseline model example
    - [ ]  Instance token vs Sample token
- [ ] Adjust our prediction result format to submission format
    - [ ] Know the current format of prediction result (@minano430)
    - [ ] New function or code to change format of prediction result

**Comment by gnsJhenJie** [comment]
# Submission format
Submission file generated from [`baseline_model_inference.py`](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/eval/prediction/baseline_model_inference.py).
`cv_preds.json`:
```json
[{
        "instance": "dc762bf1bc694d3e8141bf592f9b1456",
        "sample": "c5f58c19249d4137ae063b0e9ecd8b8e",
        "prediction": [
            [
                [660.0060751150378, 1613.625215427244],
                [660.0001502300755, 1613.6114308544882],
                [659.9942253451134, 1613.5976462817323],
                [659.9883004601512, 1613.5838617089764],
                [659.982375575189, 1613.5700771362206],
                [659.9764506902268, 1613.5562925634647],
                [659.9705258052646, 1613.5425079907088],
                [659.9646009203025, 1613.528723417953],
                [659.9586760353403, 1613.514938845197],
                [659.952751150378, 1613.5011542724412],
                [659.9468262654159, 1613.4873696996854],
                [659.9409013804537, 1613.4735851269295]
            ]
        ],
        "probabilities": [1]
    },
    {
        "instance": "dc762bf1bc694d3e8141bf592f9b1456",
        "sample": "700c1a25559b4433be532de3475e58a9",
        "prediction": [
            [
                [660.018521742971, 1613.6139279765064],
                [660.0120434859421, 1613.5988559530126],
                [660.005565228913, 1613.583783929519],
                [659.9990869718841, 1613.5687119060253],
                [659.9926087148551, 1613.5536398825318],
                [659.9861304578261, 1613.538567859038],
                [659.9796522007972, 1613.5234958355445],
                [659.9731739437682, 1613.508423812051],
                [659.9666956867393, 1613.4933517885572],
                [659.9602174297103, 1613.4782797650637],
                [659.9537391726813, 1613.46320774157],
                [659.9472609156524, 1613.4481357180764]
            ]
        ],
        "probabilities": [1]
    },
   .......
]
```
`oracle_pred.json`:
```json
[{
    "instance": "dc762bf1bc694d3e8141bf592f9b1456",
    "sample": "c5f58c19249d4137ae063b0e9ecd8b8e",
    "prediction": [
        [
            [660.0060751150378, 1613.625215427244],
            [660.0001502300755, 1613.6114308544882],
            [659.9942253451134, 1613.5976462817323],
            [659.9883004601512, 1613.5838617089764],
            [659.982375575189, 1613.5700771362206],
            [659.9764506902268, 1613.5562925634647],
            [659.9705258052646, 1613.5425079907088],
            [659.9646009203025, 1613.528723417953],
            [659.9586760353403, 1613.514938845197],
            [659.952751150378, 1613.5011542724412],
            [659.9468262654159, 1613.4873696996854],
            [659.9409013804537, 1613.4735851269295]
        ]
    ],
    "probabilities": [1]
}, {
    "instance": "dc762bf1bc694d3e8141bf592f9b1456",
    "sample": "700c1a25559b4433be532de3475e58a9",
    "prediction": [
        [
            [660.0182449881828, 1613.6132840911757],
            [660.0109364667893, 1613.5962804116898],
            [660.0030744358194, 1613.5779889615428],
            [659.9946588952732, 1613.558409740734],
            [659.9856898451505, 1613.5375427492643],
            [659.9761672854515, 1613.5153879871327],
            [659.9660912161762, 1613.49194545434],
            [659.9554616373244, 1613.467215150886],
            [659.9442785488965, 1613.4411970767703],
            [659.932541950892, 1613.4138912319936],
            [659.9202518433111, 1613.385297616555],
            [659.907408226154, 1613.3554162304554]
        ]
    ],
    "probabilities": [1]
}, 
{
    "instance": "dc762bf1bc694d3e8141bf592f9b1456",
    "sample": "747aa46b9a4641fe90db05d97db2acea",
    "prediction": [
        [
            [659.9691424946718, 1613.460942752743],
            [659.905378415679, 1613.3125920941739],
            [659.8187077630215, 1613.110948024292],
            [659.7091305366994, 1612.8560105430981],
            [659.5766467367127, 1612.5477796505918],
            [659.4212563630614, 1612.1862553467734],
            [659.2429594157453, 1611.7714376316421],
            [659.0417558947646, 1611.303326505199],
            [658.8176458001193, 1610.7819219674434],
            [658.5706291318094, 1610.2072240183757],
            [658.3007058898347, 1609.5792326579951],
            [658.0078760741955, 1608.8979478863025]
        ]
    ],
    "probabilities": [1]
    },
    .......
]
```
